extends:
  - '@commitlint/config-conventional'

rules:
  type-enum:
    - 2
    - always
    - 
      - feat      # A new feature
      - fix       # A bug fix
      - docs      # Documentation only changes
      - style     # Changes that don't affect code meaning
      - refactor  # Code change that neither fixes a bug nor adds a feature
      - perf      # Code change that improves performance
      - test      # Adding missing tests or correcting existing tests
      - build     # Changes that affect the build system or dependencies
      - ci        # Changes to CI configuration files and scripts
      - chore     # Other changes that don't modify src or test files
      - revert    # Reverts a previous commit

  scope-enum:
    - 2
    - always
    -
      - mcp       # MCP server and protocol
      - discovery # Discovery engine
      - newrelic  # New Relic client
      - config    # Configuration
      - auth      # Authentication and authorization
      - api       # REST API
      - docs      # Documentation
      - deps      # Dependencies
      - ci        # CI/CD
      - test      # Testing

  subject-case:
    - 2
    - never
    - ['upper-case', 'pascal-case']

  subject-full-stop:
    - 2
    - never
    - '.'

  header-max-length:
    - 2
    - always
    - 72

  body-leading-blank:
    - 2
    - always

  footer-leading-blank:
    - 2
    - always