version: '3.8'

services:
  # MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-server-newrelic:latest
    container_name: mcp-server-newrelic
    ports:
      - "3333:3333"   # MCP stdio/SSE port
      - "8080:8080"   # REST API port
      - "8081:8081"   # MCP HTTP port
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      # Override any specific environment variables here
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MCP_TRANSPORT=${MCP_TRANSPORT:-stdio}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mcp-network

  # Redis (for caching)
  redis:
    image: redis:7-alpine
    container_name: mcp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mcp-network:
    driver: bridge

volumes:
  redis-data:
    driver: local