global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # MCP Server metrics
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:9090']
        labels:
          environment: 'production'
          service: 'mcp-server-newrelic'
    
  # Development server metrics (when running)
  - job_name: 'mcp-server-dev'
    static_configs:
      - targets: ['mcp-dev:9090']
        labels:
          environment: 'development'
          service: 'mcp-server-newrelic'

  # Redis metrics (if exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

# Alerting rules (can be extended)
rule_files:
  # - 'alerts/*.yml'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets:
#         - 'alertmanager:9093'